### PR TITLE
Updating datatables libraries

### LINKED ISSUE #418: Reports not showing after update to Wordpress 4.3
Overview still viewable but no reports after updating to Wordpress 4.3. Tested on 2 sites with same result.

### PR DESCRIPTION
**Pull request by andizer**
Fixes #418

### CODE REVIEW

**Comment by omarreiss** [comment]
Do we really need the non-minified files here?

**Comment by andizer** [comment]
Probably yes. There is a debug mode that will load the non-minified.

**Comment by omarreiss** [comment]
Ok, so please also use the minified files in debug mode and remove the non-minified ones then.

**Comment by Rarst** [comment]
Non-minified assets in debug mode is normal and _beneficial_ practice. That's the point of debug mode. :) I am for keeping them.

**Comment by omarreiss** [comment]
Ok, so we've got a little clash of interests here with regard to dev-production. Not something to solve now. But we are going to introduce an extra constant for debugging in development, because I don't want the non-minified files to be shipped and I don't want production sites breaking in debug mode ;-)

**Pull request merged**
