### PR TITLE
Composer support

### PR DESCRIPTION
**Pull request by Rarst**
:white_check_mark: **Mergeable**.

Switched from submodules and explicit autoload to Composer.

- [x] Requires https://github.com/Yoast/api-libs/pull/18 merged and set up on Packagist first.

### CODE REVIEW

**Comment by omarreiss** [comment]
@Rarst I think you only need to update `.travis.yml` like you did for wordpress-seo before I can merge.

**Comment by Rarst** [comment]
Having trouble getting test to pass:

```
PHP Fatal error:  Class 'Yoast_Google_Analytics_Client' not found in /tmp/wordpress/src/wp-content/plugins/google-analytics-for-wordpress/admin/class-google-analytics.php on line 201
Fatal error: Class 'Yoast_Google_Analytics_Client' not found in /tmp/wordpress/src/wp-content/plugins/google-analytics-for-wordpress/admin/class-google-analytics.php on line 201
```

This isn't part of Composer autoload since api-libs is using its own load process (which I hadn't touched), but can't figure out what I need to do for test to pick it up. Plugin itself works just fine.

**Comment by omarreiss** [comment]
@jdevalk could you merge this and publish to packagist?

**Comment by jdevalk** [comment]
Done and done

**Pull request merged**
