### PR TITLE
Added 'label_for' key to $args when callin add_settings_field

### PR DESCRIPTION
**Pull request by steverep**
This change is to address issue #313, at least for those settings rendered using the settings API with the `do_settings_sections()` function.  It looks like there may be some labeling issues which remain for input fields not using he API.

Per the Wordpress codex for `add_settings_field(...)`, the 'label_for' key
will be used to wrap a `<label>` tag around the setting `$title`. with the
value as the corresponding input field `id`.  This change adds this key so
that fields using it will be labeled when rendered.  Also, the potential
callback functions are modified to use this additional array key for
consistency.

### CODE REVIEW

**Comment by steverep** [comment]
The second commit is what I could find of other mis-labeled fields, but I don't promise I've found them all and I'm going to turn it over to the Yoast team from here.  Regarding the last commit, also consider the following:

* In admin/pages/settings-api.php, lines 55-56 really make no sense (a label tag is wrapped around a \&nbsp; and is not even associated with the input tag, but is pointless to do so since it has no text).  Consider just making a button tag instead - much cleaner and no label required.
* in admin/pages/dashboard.php, the select tag which I labeled is not accessible itself (i.e. a screen reader should ideally treat this as any other drop-down and announce the options, but it doesn't).  A quick Google search looks like using the data-rel attribute might be the issue and not a valid way to do this, but I'm not a JQuery expert so I'll leave that to you guys.
* Neither of the 2 labels/fields were wrapped in a form tag, which I'm not sure is valid HTML5.

**Comment by steverep** [comment]
Alright, that last commit was to correct a bullet point I made in a previous comment.  I wasn't paying close enough attention to realize the input field was a button, and so it doesn't require a label beyond its text value.  So I simply deleted the unnecessary line of code... I'm done now.  Please review :).

**Comment by jdevalk** [comment]
:+1: from me. @omarreiss will test and merge if it all works :) thanks man, great pull!

**Comment by omarreiss** [comment]
Acceptance testing: :white_check_mark:

**Pull request merged**
